### ISSUE TITLE
Highlight due date if the issue is delayed

### ISSUE THREAD

**Issue by vividtone** [redmica/redmine_issues_panel#16]
In the default issue view (/issues/:id), the due date is highlighted if the issues is delayed. I think it would be nice and consistent if the due date in Issues Panel is also highlighted.

Default issue view:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/114863/87636833-496d6680-c77c-11ea-9674-4377ba6c4aed.png">

Issues Panel:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/114863/87636875-58ecaf80-c77c-11ea-9cb5-506e5f1a15ea.png">

**Comment by takenory** [comment]
Thank you for your feedback.
That's a proposal for convenience and consistency.
I implemented it right away!
