### ISSUE TITLE
Redmine4.0で利用できないですか？

### ISSUE THREAD

**Issue by lornwolf** [redmica/redmine_issues_panel#18]
Redmine4.0で下記のエラーが発生しました。

Started GET "/redmine/projects/xxxxx/issues_panel" for x.x.x.x at 2020-08-12 11:04:47 +0800
Processing by IssuesPanelController#index as HTML
  Parameters: {"project_id"=>"xxxxx"}
  Current user: xxxxxxxx (id=6)
Completed 500 Internal Server Error in 47ms (ActiveRecord: 6.0ms)
  
NameError (uninitialized constant Redmine::Helpers::IssuesPanel
Did you mean?  IssuesPanel):
  
plugins/redmine_issues_panel/app/controllers/issues_panel_controller.rb:36:in `retrieve_issue_panel'
plugins/redmine_issues_panel/app/controllers/issues_panel_controller.rb:12:in `index'

**Comment by takenory** [comment]
プラグインを試していただきありがとうございます。
`Query#display_type` や `Query#available_display_types` など、Redmine4.0には追加されていないメソッドを呼び出している箇所がありますので、Redmine4.0では利用できないと思います 🙇 
プラグインを利用いただく場合は、Redmica または Redmine4.1 の利用をご検討ください。

**Comment by lornwolf** [comment]
ご回答いただきありがとうございます。
一部Redmine4.0のない関数・クラスを4.1から移植して、Redmine4.0で本プラグインを動かせました。
