### ISSUE TITLE
翻訳メッセージが正しく表示されない

### ISSUE THREAD

**Issue by wate** [redmica/redmine_issues_panel#29]
概要
------------------

翻訳メッセージが正しく表示されない

再現手順
------------------

1. チケットパネルの画面に遷移する
2. 各ステータス列にある「新しいチケット」をクリックする
3. 新しいチケット登録用のモーダルを表示させる

実際の挙動
------------------

「担当者」項目の下部に以下のメッセージが表示される

```
translation missing: ja.label_assign_to_me
```

### 補足

以下で、「label_assign_to_me」の文言を出力しようとしているが、

https://github.com/redmica/redmine_issues_panel/blob/master/app/views/issues_panel/_modal_form.html.erb#L53

以下の翻訳データには該当の翻訳メッセージが存在していないため、

https://github.com/redmica/redmine_issues_panel/blob/master/config/locales/ja.yml

上記の事象が出ているものと思われる。

想定する挙動
------------------

「担当者を自分に割り当てる」旨のメッセージが表示される。

**Comment by takenory** [comment]
バグの報告ありがとうございます。
「label_assign_to_me」は、Redmine 4.2 から加わった翻訳設定であったため
Redmine 4.1では報告いただいた通りtranslation missingとなってしまうようです。
プラグイン側の翻訳データを修正します。

**Comment by takenory** [comment]
@wate
b503c67 のコミットで翻訳メッセージが正しく表示されない問題に対処しました。

**Comment by wate** [comment]
@takenory 対応ありがとうございました!
