### ISSUE TITLE
LoadError during startup with Redmine trunk r21288

### ISSUE THREAD

**Issue by vividtone** [redmica/redmine_issues_panel#32]
Redmine Issues Panel plugin cannot run with Redmine trunk r21288. With the plugin installed, the following error occurs during startup and Redmine cannot be started.

Probably this is due to https://www.redmine.org/issues/32938.

```
/path/to/gems/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- queries_controller_patch (LoadError)
```

**Comment by takenory** [comment]
@vividtone  
Thanks for reporting the problem.
As you pointed out, it was affected by the Zeitwerk support implemented in r21288.

I made a PR #33 that fixes the issue, could you try it in your environment?

**Comment by takenory** [comment]
I have confirmed that it works fine with RedMica 1.3, 2.0 and Redmine r21288.
I'm going to merge the PR of #33.
