### ISSUE TITLE
Top level panel shows all statuses, despite tracker selection

### ISSUE THREAD

**Issue by salmanmp** [redmica/redmine_issues_panel#39]
Hi
In the path {redmine}/issues_panel, Panel shows all statuses, even if you select and limit trackers.
It is expected that statuses must filtered to selected trackers statuses, based on those tracker workflows.

**Comment by takenory** [comment]
@salmanmp Thanks for the feedback.
We are working on a PR (#44) to respond to the feedback you sent.

**Comment by takenory** [comment]
Merged PR #44 to master!

@salmanmp
Could you please confirm that the latest master branch resolves the issue you reported?

**Comment by takenory** [comment]
Thanks for reporting the issue and for the review!
I'll close the issue.
