### ISSUE TITLE
It's too better not to ignore hooks on updating issues

### ISSUE THREAD

**Issue by salmanmp** [redmica/redmine_issues_panel#41]
After moving an IssueCard, there is a function `move!` in `IssueCard` model that saves changes on issue by itself and ignores hooks like `controller_issues_edit_before_save` and `controller_issues_edit_after_save`.
Many of other plugins may be developed in way that do changes on issue by defining related hooks.

**Comment by salmanmp** [comment]
Any plugin that wants to make changes to an issue or do anything else after creating/changing an issue is officially referred to using these hooks.
For example, when the plugin wants to create another issue after changing the status of an issue, if it wents to desired situation.

> I think the hook you gave us as an example is what the plugin calls to override the update operation on the issue screen

There are two type of hooks. These hooks are `controller hooks` and Redmine call many of theme in some points of code in `Controllers`.

**Comment by takenory** [comment]
> For example, when your plugin wants to create another issue after changing the status of an issue, if it wents to desired status.

I think it is more appropriate to use AR model callbacks such as after_save, when a plugin overrides data operations that independent from controller.

To show changes behind the user's D&D operations (adding issues, setting assignee, etc.) would require reloading the whole panel, but the current D&D operations are not implemented that way.

It might be possible to check for changes that are not in the D&D (such as the number of issues to be displayed in the panel) before and after the D&D operation, and indicate the need for reloading.

**Comment by takenory** [comment]
Thanks for the reaction @salmanmp.
I'll close the issue.

**Comment by salmanmp** [comment]
I'm Sorry.
I sent reaction :+1: to show that I'm agree; And it seems the latest solution is not perfect but it will work.
