### ISSUE TITLE
New group does not appears

### ISSUE THREAD

**Issue by salmanmp** [redmica/redmine_issues_panel#42]
If you grouped issues panel, and one of group items has no card, say grouped by Status*, and all card are in `ToDo` at start. If you move a card to `Doing`, that card got hidden and `Doing` group does not appears.

*:May be grouping by status is not useful, but some other plugins could change attributes on changing status (moving cards) and if you grouped issues by that attribute, new groups does not shown.

**Comment by takenory** [comment]
@salmanmp Thanks for the feedback.
The latest version of the issues panel does not allow grouping by status (you can set a status on a grouper, but it does not work).

> *:May be grouping by status is not useful, but some other plugins could change attributes on changing status (moving cards) and if you grouped issues by that attribute, new groups does not shown.

Could you explain in more detail what the specific plugin features are that change attributes by status changes?

**Comment by takenory** [comment]
Based on the current implementation of the issue panel, it may be possible to implement the solution I commented on here https://github.com/redmica/redmine_issues_panel/issues/41#issuecomment-1183924634.

**Comment by takenory** [comment]
Thanks for the reaction @salmanmp.
I'll close the issue.
